name: Browser Compatibility Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  browser-compatibility:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          yarn install
      
      - name: Build packages
        run: yarn build
      
      - name: Validate browser bundle
        run: yarn validate-browser-bundle
      
      - name: Run browser compatibility tests
        run: yarn test:browser-compatibility
      
      - name: Run platform adapter tests
        run: yarn test:platform-adapters
      
      - name: Run runtime feature detection tests
        run: yarn test:runtime-features
      
      - name: Analyze bundle
        run: yarn analyze-bundle
      
      - name: Monitor bundle size
        run: yarn monitor-bundle-size
      
      - name: Generate bundle size report
        run: yarn monitor-bundle-size:report
      
      - name: Upload bundle size report
        uses: actions/upload-artifact@v4
        with:
          name: bundle-size-report
          path: dist/bundle-size-report.html
      
      - name: Upload bundle stats
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: dist/stats-*.html